### ISSUE TITLE
Vermutung: GitHub-Workflow Cache hat Nebeneffekte

### ISSUE THREAD

**Issue by deleonio** [DiPA-Projekt/dipa-hub#228]
Ich habe den aktuellen Stand des Projektassistenten übernommen. Der fehlerfrei ist. Sowohl local als auch remote.

Link zu Projektassistent Build: https://github.com/DiPA-Projekt/projektassistent/actions/runs/634570665

Doch im DiPA-Repo schlagen Fehler an: https://github.com/DiPA-Projekt/dipa-hub/runs/2062847572

Ich vermute, dass die node_modules ggf. nicht exakt gleich installiert werden.

Code-Rev.: https://github.com/DiPA-Projekt/dipa-hub/commit/45ee80ec02f350f4ae0a6fde8ea394bda3d9218f

**Comment by beckerjohannes** [comment]
Ein Problem des Workflow cache ist es definitiv nicht, da der "mvn clean install" auch bei mir lokal fehl schlägt.

**Comment by beckerjohannes** [comment]
Wenn ich das ganze im VS-Code aufmache dann kriege ich folgenden in der 

![image](https://user-images.githubusercontent.com/56342691/110453935-01160680-80c7-11eb-8b30-b95f8f646fa6.png)

In der folgenden Klasse:

![image](https://user-images.githubusercontent.com/56342691/110454029-15f29a00-80c7-11eb-8cf0-96b9add9a384.png)

Ich würde vermuten, dass sich etwas an der OpenAPI Definition geändert hat und Du das lokal nicht mitbekommst weil das Löschen des generierten OpenAPI-Source nicht übernommen wurde.
