### ISSUE TITLE
Probleme mit den GitHub Workflow

### ISSUE THREAD

**Issue by deleonio** [DiPA-Projekt/dipa-hub#235]
Wir haben sowohl bei dipa-hub, als auch beim projektassistenten fehlschlagende Builds.

Es gibt immer das gleiche Fehlerbild:

https://github.com/DiPA-Projekt/projektassistent/pull/42/checks?check_run_id=2111152291

![image](https://user-images.githubusercontent.com/6279703/111133472-dd493980-857a-11eb-9727-5f9202b8f4b3.png)

https://github.com/DiPA-Projekt/dipa-hub/pull/233/checks?check_run_id=2110599715

![image](https://user-images.githubusercontent.com/6279703/111133549-f18d3680-857a-11eb-8726-e087f7fdedf0.png)

**Comment by Bock4Soft** [comment]
@deleonio das betrifft merkwürdigerweise offensichtlich nur Builds vom Bot

**Comment by beckerjohannes** [comment]
Problem nicht gelöst... manueller Rerun der Workflows läuft unter anderen Permissions. Siehe https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot

**Comment by beckerjohannes** [comment]
Fixed via referenced commit.
